apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pysmoke.fullname" . }}-instances
  labels:
    app.kubernetes.io/name: {{ include "pysmoke.name" . }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
data:
  instances.json: |
{{ .Values.smokeTest.instancesJson | indent 4 }}
